"""
Model card generation (MLOps §4.4 / EU AI Act 2024/1689 Annex IV).

Renders a Markdown model card from the training metadata + evaluation summary so
every registered model version ships with human-readable documentation of its
intended use, data, metrics, limitations and regulatory considerations.
"""
from __future__ import annotations


def render_model_card(version: str, stage: str, meta: dict, summary: dict,
                      promotion: dict) -> str:
    hp = meta.get("hyperparams", {})
    conv = summary.get("convergence", {})
    b = summary.get("benchmark", {})
    fid = summary.get("fidelity", {})
    ppo = b.get("rl_ppo", {}).get("mean_reward")
    grd = b.get("greedy", {}).get("mean_reward")
    rnd = b.get("random", {}).get("mean_reward")
    csc = b.get("cascade", {}).get("mean_reward")
    pat = b.get("patient", {}).get("mean_reward")

    def _num(x, nd=2):
        return f"{x:.{nd}f}" if isinstance(x, (int, float)) else "—"

    extra_baselines = ""
    if csc is not None:
        extra_baselines += f"| Reward — cascade (production-heuristic proxy) | {_num(csc)} |\n"
    if pat is not None:
        extra_baselines += f"| Reward — patient (anticipatory heuristic) | {_num(pat)} |\n"

    if promotion.get("surpasses_greedy"):
        greedy_limitation = (
            "- **Surpasses the greedy heuristic in the anticipatory formulation** "
            "(phase 2: event-driven cruise waves, driver contention, hold actions, "
            "hard all-aboard deadlines). In the phase-1 myopic formulation greedy "
            "was optimal by construction — documented in thesis §4.2 as the finding "
            "that motivated the environment redesign.\n"
            "- The hold decision (waiting for a driver about to free up) is expressed "
            "in simulation; the serving path exposes an advisory ranking, where a "
            "hold surfaces as ranking a soon-to-free driver above distant free ones."
        )
    else:
        greedy_limitation = (
            "- **Does not surpass the greedy heuristic.** Greedy (nearest-ETA) is "
            "near-optimal in the myopic single-dispatch formulation (the target "
            "request is fixed each step, so the only controllable quantity is the "
            "chosen driver's ETA, which greedy minimises)."
        )

    return f"""# Model Card — CruiseDispatch PPO agent

| | |
|---|---|
| **Version** | `{version}` |
| **Stage** | `{stage}` |
| **Trained at** | {meta.get('lastTrainedAt', '—')} |
| **Git SHA** | `{meta.get('gitSha', '—')}` |
| **Framework** | Stable-Baselines3 · PPO (`MlpPolicy`) |
| **Total timesteps** | {meta.get('totalTimesteps', '—')} |
| **Domain randomization** | {meta.get('domainRandomization', '—')} |

## Intended use
Advisory ranking of available drivers for the most-urgent pending pickup request
in City2Cruise. The ranking is **advisory**: the dispatch layer applies it only
when `RL_ROUTING_ENABLED=true` and always falls back to geo-distance if the model
is slow/unavailable. Final oversight is human-in-the-loop via the Control Tower
(EU AI Act Art. 14).

## Training data
Fully **synthetic** episodes generated by `rl_service/train_tfm.py` with domain
randomization (Tobin et al., 2017). No personal or production data is used
(confidentiality annex). Reproducible: fixed seed 42, pinned dependencies.

## Hyperparameters
`lr={hp.get('learning_rate')}`, `n_steps={hp.get('n_steps')}`,
`batch_size={hp.get('batch_size')}`, `n_epochs={hp.get('n_epochs')}`,
`gamma={hp.get('gamma')}`, `gae_lambda={hp.get('gae_lambda')}`,
`clip_range={hp.get('clip_range')}`, `ent_coef={hp.get('ent_coef')}`,
`net_arch={hp.get('net_arch')}`.

## Metrics (held-out, 1000 episodes)
| Metric | Value |
|---|---|
| Convergence mean reward | {_num(conv.get('mean_reward'))} (coeff_var {_num(conv.get('coeff_var'), 3)}) |
| Reward — PPO | {_num(ppo)} |
| Reward — greedy (myopic baseline) | {_num(grd)} |
| Reward — random (baseline) | {_num(rnd)} |
{extra_baselines}| Improvement vs random | {_num(promotion.get('reward_vs_random_pct', 0) * 100, 1)} % |
| Ratio vs greedy | {_num(promotion.get('reward_vs_greedy_ratio'), 3)} |
| Reality gap (avg / p95) | {_num(fid.get('delta_avg_pct', 0) * 100, 1)} % / {_num(fid.get('delta_p95_pct', 0) * 100, 1)} % |

## Evaluation / promotion decision
Promotion policy (`rl_service/validation/promotion.py`): **{'PROMOTE' if promotion.get('promote') else 'HOLD'}**
— checks: {promotion.get('checks')}.

## Limitations
{greedy_limitation}
- Sim-to-real fidelity is measured against representative reference fixtures, not
  live production telemetry (future work).
- Trained on synthetic data only.

## Regulatory considerations (EU Reg. 2024/1689)
- **Art. 12 record-keeping** — predictions logged to `rl_inference_log`; runs tracked in MLflow.
- **Art. 14 human oversight** — advisory output + Control Tower manual intervention + geo fallback.
- **Art. 15 accuracy/robustness** — release gate (convergence/fidelity/robustness) + drift monitoring.
- **Art. 17 quality management** — versioned registry, promotion gate, reproducible CI training.
"""
